// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	replication "github.com/fyerfyer/fyer-cache/cache/replication"
	mock "github.com/stretchr/testify/mock"
)

// FollowerNode is an autogenerated mock type for the FollowerNode type
type FollowerNode struct {
	mock.Mock
}

type FollowerNode_Expecter struct {
	mock *mock.Mock
}

func (_m *FollowerNode) EXPECT() *FollowerNode_Expecter {
	return &FollowerNode_Expecter{mock: &_m.Mock}
}

// ApplyEntry provides a mock function with given fields: ctx, entry
func (_m *FollowerNode) ApplyEntry(ctx context.Context, entry *replication.ReplicationEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for ApplyEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *replication.ReplicationEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_ApplyEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyEntry'
type FollowerNode_ApplyEntry_Call struct {
	*mock.Call
}

// ApplyEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *replication.ReplicationEntry
func (_e *FollowerNode_Expecter) ApplyEntry(ctx interface{}, entry interface{}) *FollowerNode_ApplyEntry_Call {
	return &FollowerNode_ApplyEntry_Call{Call: _e.mock.On("ApplyEntry", ctx, entry)}
}

func (_c *FollowerNode_ApplyEntry_Call) Run(run func(ctx context.Context, entry *replication.ReplicationEntry)) *FollowerNode_ApplyEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*replication.ReplicationEntry))
	})
	return _c
}

func (_c *FollowerNode_ApplyEntry_Call) Return(_a0 error) *FollowerNode_ApplyEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_ApplyEntry_Call) RunAndReturn(run func(context.Context, *replication.ReplicationEntry) error) *FollowerNode_ApplyEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeader provides a mock function with no fields
func (_m *FollowerNode) GetLeader() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLeader")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FollowerNode_GetLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeader'
type FollowerNode_GetLeader_Call struct {
	*mock.Call
}

// GetLeader is a helper method to define mock.On call
func (_e *FollowerNode_Expecter) GetLeader() *FollowerNode_GetLeader_Call {
	return &FollowerNode_GetLeader_Call{Call: _e.mock.On("GetLeader")}
}

func (_c *FollowerNode_GetLeader_Call) Run(run func()) *FollowerNode_GetLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FollowerNode_GetLeader_Call) Return(_a0 string) *FollowerNode_GetLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_GetLeader_Call) RunAndReturn(run func() string) *FollowerNode_GetLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetLog provides a mock function with no fields
func (_m *FollowerNode) GetLog() replication.ReplicationLog {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLog")
	}

	var r0 replication.ReplicationLog
	if rf, ok := ret.Get(0).(func() replication.ReplicationLog); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(replication.ReplicationLog)
		}
	}

	return r0
}

// FollowerNode_GetLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLog'
type FollowerNode_GetLog_Call struct {
	*mock.Call
}

// GetLog is a helper method to define mock.On call
func (_e *FollowerNode_Expecter) GetLog() *FollowerNode_GetLog_Call {
	return &FollowerNode_GetLog_Call{Call: _e.mock.On("GetLog")}
}

func (_c *FollowerNode_GetLog_Call) Run(run func()) *FollowerNode_GetLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FollowerNode_GetLog_Call) Return(_a0 replication.ReplicationLog) *FollowerNode_GetLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_GetLog_Call) RunAndReturn(run func() replication.ReplicationLog) *FollowerNode_GetLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with no fields
func (_m *FollowerNode) GetRole() replication.ReplicationRole {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 replication.ReplicationRole
	if rf, ok := ret.Get(0).(func() replication.ReplicationRole); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(replication.ReplicationRole)
	}

	return r0
}

// FollowerNode_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type FollowerNode_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
func (_e *FollowerNode_Expecter) GetRole() *FollowerNode_GetRole_Call {
	return &FollowerNode_GetRole_Call{Call: _e.mock.On("GetRole")}
}

func (_c *FollowerNode_GetRole_Call) Run(run func()) *FollowerNode_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FollowerNode_GetRole_Call) Return(_a0 replication.ReplicationRole) *FollowerNode_GetRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_GetRole_Call) RunAndReturn(run func() replication.ReplicationRole) *FollowerNode_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// HandleHeartbeat provides a mock function with given fields: ctx, leaderID, term
func (_m *FollowerNode) HandleHeartbeat(ctx context.Context, leaderID string, term uint64) error {
	ret := _m.Called(ctx, leaderID, term)

	if len(ret) == 0 {
		panic("no return value specified for HandleHeartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = rf(ctx, leaderID, term)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_HandleHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleHeartbeat'
type FollowerNode_HandleHeartbeat_Call struct {
	*mock.Call
}

// HandleHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - leaderID string
//   - term uint64
func (_e *FollowerNode_Expecter) HandleHeartbeat(ctx interface{}, leaderID interface{}, term interface{}) *FollowerNode_HandleHeartbeat_Call {
	return &FollowerNode_HandleHeartbeat_Call{Call: _e.mock.On("HandleHeartbeat", ctx, leaderID, term)}
}

func (_c *FollowerNode_HandleHeartbeat_Call) Run(run func(ctx context.Context, leaderID string, term uint64)) *FollowerNode_HandleHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64))
	})
	return _c
}

func (_c *FollowerNode_HandleHeartbeat_Call) Return(_a0 error) *FollowerNode_HandleHeartbeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_HandleHeartbeat_Call) RunAndReturn(run func(context.Context, string, uint64) error) *FollowerNode_HandleHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteToLeader provides a mock function with given fields: ctx
func (_m *FollowerNode) PromoteToLeader(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PromoteToLeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_PromoteToLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteToLeader'
type FollowerNode_PromoteToLeader_Call struct {
	*mock.Call
}

// PromoteToLeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FollowerNode_Expecter) PromoteToLeader(ctx interface{}) *FollowerNode_PromoteToLeader_Call {
	return &FollowerNode_PromoteToLeader_Call{Call: _e.mock.On("PromoteToLeader", ctx)}
}

func (_c *FollowerNode_PromoteToLeader_Call) Run(run func(ctx context.Context)) *FollowerNode_PromoteToLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FollowerNode_PromoteToLeader_Call) Return(_a0 error) *FollowerNode_PromoteToLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_PromoteToLeader_Call) RunAndReturn(run func(context.Context) error) *FollowerNode_PromoteToLeader_Call {
	_c.Call.Return(run)
	return _c
}

// RequestSync provides a mock function with given fields: ctx, target, req
func (_m *FollowerNode) RequestSync(ctx context.Context, target string, req *replication.SyncRequest) (*replication.SyncResponse, error) {
	ret := _m.Called(ctx, target, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestSync")
	}

	var r0 *replication.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *replication.SyncRequest) (*replication.SyncResponse, error)); ok {
		return rf(ctx, target, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *replication.SyncRequest) *replication.SyncResponse); ok {
		r0 = rf(ctx, target, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*replication.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *replication.SyncRequest) error); ok {
		r1 = rf(ctx, target, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FollowerNode_RequestSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestSync'
type FollowerNode_RequestSync_Call struct {
	*mock.Call
}

// RequestSync is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
//   - req *replication.SyncRequest
func (_e *FollowerNode_Expecter) RequestSync(ctx interface{}, target interface{}, req interface{}) *FollowerNode_RequestSync_Call {
	return &FollowerNode_RequestSync_Call{Call: _e.mock.On("RequestSync", ctx, target, req)}
}

func (_c *FollowerNode_RequestSync_Call) Run(run func(ctx context.Context, target string, req *replication.SyncRequest)) *FollowerNode_RequestSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*replication.SyncRequest))
	})
	return _c
}

func (_c *FollowerNode_RequestSync_Call) Return(_a0 *replication.SyncResponse, _a1 error) *FollowerNode_RequestSync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FollowerNode_RequestSync_Call) RunAndReturn(run func(context.Context, string, *replication.SyncRequest) (*replication.SyncResponse, error)) *FollowerNode_RequestSync_Call {
	_c.Call.Return(run)
	return _c
}

// SetRole provides a mock function with given fields: role
func (_m *FollowerNode) SetRole(role replication.ReplicationRole) {
	_m.Called(role)
}

// FollowerNode_SetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRole'
type FollowerNode_SetRole_Call struct {
	*mock.Call
}

// SetRole is a helper method to define mock.On call
//   - role replication.ReplicationRole
func (_e *FollowerNode_Expecter) SetRole(role interface{}) *FollowerNode_SetRole_Call {
	return &FollowerNode_SetRole_Call{Call: _e.mock.On("SetRole", role)}
}

func (_c *FollowerNode_SetRole_Call) Run(run func(role replication.ReplicationRole)) *FollowerNode_SetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(replication.ReplicationRole))
	})
	return _c
}

func (_c *FollowerNode_SetRole_Call) Return() *FollowerNode_SetRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *FollowerNode_SetRole_Call) RunAndReturn(run func(replication.ReplicationRole)) *FollowerNode_SetRole_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *FollowerNode) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type FollowerNode_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *FollowerNode_Expecter) Start() *FollowerNode_Start_Call {
	return &FollowerNode_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *FollowerNode_Start_Call) Run(run func()) *FollowerNode_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FollowerNode_Start_Call) Return(_a0 error) *FollowerNode_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_Start_Call) RunAndReturn(run func() error) *FollowerNode_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *FollowerNode) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type FollowerNode_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *FollowerNode_Expecter) Stop() *FollowerNode_Stop_Call {
	return &FollowerNode_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *FollowerNode_Stop_Call) Run(run func()) *FollowerNode_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FollowerNode_Stop_Call) Return(_a0 error) *FollowerNode_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_Stop_Call) RunAndReturn(run func() error) *FollowerNode_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SyncFromLeader provides a mock function with given fields: ctx
func (_m *FollowerNode) SyncFromLeader(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncFromLeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNode_SyncFromLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncFromLeader'
type FollowerNode_SyncFromLeader_Call struct {
	*mock.Call
}

// SyncFromLeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FollowerNode_Expecter) SyncFromLeader(ctx interface{}) *FollowerNode_SyncFromLeader_Call {
	return &FollowerNode_SyncFromLeader_Call{Call: _e.mock.On("SyncFromLeader", ctx)}
}

func (_c *FollowerNode_SyncFromLeader_Call) Run(run func(ctx context.Context)) *FollowerNode_SyncFromLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FollowerNode_SyncFromLeader_Call) Return(_a0 error) *FollowerNode_SyncFromLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FollowerNode_SyncFromLeader_Call) RunAndReturn(run func(context.Context) error) *FollowerNode_SyncFromLeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewFollowerNode creates a new instance of FollowerNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFollowerNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *FollowerNode {
	mock := &FollowerNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
